/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/authbook/': RouteRecordInfo<'/authbook/', '/authbook', Record<never, never>, Record<never, never>>,
    '/ca-auth/': RouteRecordInfo<'/ca-auth/', '/ca-auth', Record<never, never>, Record<never, never>>,
    '/gama-bigdata/': RouteRecordInfo<'/gama-bigdata/', '/gama-bigdata', Record<never, never>, Record<never, never>>,
    '/id-card-upload/': RouteRecordInfo<'/id-card-upload/', '/id-card-upload', Record<never, never>, Record<never, never>>,
    '/last-examine/': RouteRecordInfo<'/last-examine/', '/last-examine', Record<never, never>, Record<never, never>>,
    '/pay/': RouteRecordInfo<'/pay/', '/pay', Record<never, never>, Record<never, never>>,
    '/phone-login/': RouteRecordInfo<'/phone-login/', '/phone-login', Record<never, never>, Record<never, never>>,
    'upload-zhengxin': RouteRecordInfo<'upload-zhengxin', '/upload-zhengxin', Record<never, never>, Record<never, never>>,
  }
}
